version: '3.1'

services:
  gateway:
    container_name: gateway
    restart: unless-stopped

    build:
      context: ./gateway
      dockerfile: Dockerfile

    ports:
      - '5000:5000'
    volumes:
      - ./gateway:/usr/src/app

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - icarus-data:/data/db

volumes:
  icarus-data:
