version: '3.1'

services:
  gateway:
    container_name: gateway
    restart: unless-stopped

    build:
      context: ./gateway
      dockerfile: Dockerfile

    ports:
      - 5000:5000
    depends_on:
      - mongodb
      - cassandra
      - mysql
      - mssql
    networks:
      - gateway-network
    volumes:
      - ./gateway:/usr/src/app

  mongodb:
    container_name: mongodb_icarus
    image: mongo:6.0
    volumes:
      - ~/mongo:/data/db
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    networks:
      - gateway-network

  mysql:
    container_name: mysql_icarus
    image: mysql:8.0
    volumes:
      - db:/var/lib/mysql
    ports:
      - '3310:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - gateway-network

networks:
  gateway-network:
    driver: bridge

volumes:
  db:
