version: '3.1'

services:
  gateway:
    container_name: gateway
    restart: unless-stopped

    build:
      context: ./gateway
      dockerfile: Dockerfile

    ports:
      - '5000:5000'
    volumes:
      - ./gateway:/usr/src/app

  mongodb:
    image: mongo:6-jammy
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - icarus-data:/data/db

  prisma:
    container_name: prisma
    build:
      context: ./gateway
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    environment:
      DATABASE_URL: mongodb://localhost:27017/icarus-test
    volumes:
      - ./prisma:/app
volumes:
  icarus-data:
