version: '3.1'

services:
  gateway:
    container_name: gateway
    restart: unless-stopped

    build:
      context: ./gateway
      dockerfile: Dockerfile

    ports:
      - 5000:5000

    volumes:
      - ./gateway:/usr/src/app
