{
 "title": "Apollo GraphQL",
 "description": "Apollo GraphQL metrics. Mutations/errors/operations.",
 "tags": [
  "graphql",
  "prometheus",
  "nestjs"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(graphql_queries_responded, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Queries",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(graphql_queries_resolved{instance=\"$instance\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Success Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - sum(graphql_queries_errored{job=\"icarus-monitoring\", operation=~\"(query|mutation)\"}) / sum(graphql_queries_responded{job=\"icarus-monitoring\", operation=~\"(query|mutation)\"})) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(graphql_queries_errored{instance=\"icarus-api:5001\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Query Errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(graphql_queries_errored{instance=\"icarus-api:5001\", operation=\"query\"})"
    }
   ]
  },
  {
   "title": "Mutation Errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(graphql_queries_errored{instance=\"icarus-api:5001\", operation=\"mutation\"})"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (operation, operationName) (graphql_queries_errored{job=\"icarus-monitoring\", operation=~\"(query|mutation)\"})\n"
    }
   ]
  },
  { "title": "Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Queries",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(graphql_queries_resolved{instance=\"icarus-api:5001\", operation=\"query\"}[24h])) by (operationName) > 0"
    }
   ]
  },
  {
   "title": "Mutations",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(graphql_queries_resolved{instance=\"icarus-api:5001\", operation=\"mutation\"}[24h])) by (operationName) > 0"
    }
   ]
  },
  {
   "title": "Total numbers of Queries Resolved",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "graphql_queries_resolved{instance=\"icarus-api:5001\", operation=\"query\"}",
     "legendFormat": "{{operationName}}"
    }
   ]
  },
  {
   "title": "Total numbers of Mutations Resolved",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "graphql_queries_resolved{instance=\"$instance\", operation=\"mutation\"}",
     "legendFormat": "{{operationName}}"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Avg time in seconds to execute query",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "seconds" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(graphql_execution_time_sum[24h]) / rate(graphql_execution_time_count[24h])\n\n",
     "legendFormat": "{{operationName}}"
    }
   ]
  },
  {
   "title": "Avg time in seconds to resolve a query ",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "seconds" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(graphql_resolution_time_sum[$__rate_interval]) / rate(graphql_resolution_time_count[$__rate_interval])\n\n",
     "legendFormat": "{{operationName}}"
    }
   ]
  }
 ]
}