version: '3.2'

services:
  api:
    image: 352074856451.dkr.ecr.eu-north-1.amazonaws.com/icarus-fast-api:latest
    build:
      context: ../src
      dockerfile: Dockerfile
    ports:
      - 5001:5001
    networks:
      - icarus-stack_monitoring

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    networks:
      - icarus-stack_monitoring

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - 3000:3000
    networks:
      - icarus-stack_monitoring

networks:
  icarus-stack_monitoring:
    driver: overlay

volumes:
  prometheus-data: {}
  grafana-data: {}
