import { GraphQLError } from 'graphql';

// By default the error message generated by AuthenticationError will be the one selected below. But
// we can costumize our resolver errors with a different message with the AuthenticationError class.
// Examples of messages: "Please provide email and password",
// "Incorrect email or password",
// "The user belonging to this token does no longer exists",
// "User recently changed password! Please log in again",
// "There is no user with that email address",
// "Token is invalid or expired. Please log in again!",
// "Your current password is wrong"...

class AuthenticationError extends GraphQLError {
  constructor(message) {
    super(message || 'You are not logged in ! Please log in to get access.', {
      extensions: {
        code: 'UNAUTHENTICATED',
      },
    });
  }
}

export { AuthenticationError };
