spectaql:
  logoFile: ../api/src/docs/images/icarus_logo.jpeg
  preserveLogoName: true
  logoHeightPx: 200
  faviconFile: ../api/src/docs/images/favicon.ico
  displayAllServers: true

introspection:
  url: http://13.53.175.139:5001/
  removeTrailingPeriodFromDescriptions: false
  queryNameStrategy: capitalizeFirst
  fieldExpansionDepth: 3

  # Hide any Types that are not used anywhere in your schema after other things have been hidden.
  # Default: true
  hideUnusedTypes: true

  # Whether to document any Types at all
  # Default: true
  objectsDocumentedDefault: true
  # Whether to document an individual Type, in the absence of a metadata directive
  # Default: true
  objectDocumentedDefault: true

  # Whether to document any Input Object types at all
  # Default: true
  inputsDocumentedDefault: true
  # Whether to document an individual Input Object, in the absence of a metadata directive
  # Default: true
  inputDocumentedDefault: true

  # Whether to document any Enums at all
  # Default: true
  enumsDocumentedDefault: true
  # Whether to document an individual Enum, in the absence of a metadata directive
  # Default: true
  enumDocumentedDefault: true

info:
  title: Icarus API Documentation
  description: Welcome to the Icarus API Reference. This reference includes the complete set of GraphQL types, queries, mutations, and their parametes. Learn how to authenticate to the api in the Getting Started.
  termsOfService: https://www.icarus.com/terms
  contact:
    name: API Support
    url: http://www.icarus.com/support
    email: support@icarus.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://13.53.175.139:5001/
    description: Development
